- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: enable nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: disable default host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
  - restart nginx
