- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: install docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest

- name: add user pi to group docker
  user:
    name: pi
    groups: docker
    append: yes
