- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    id: "0EBFCD88"

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: install docker and dependencies
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-dev
    - python3-pip
    state: latest

# Requred to use docker_container
- name: install docker module for python
  pip:
    name: docker

- name: add user pi to group docker
  user:
    name: pi
    groups: docker
    append: yes
