all:
  hosts:
    smarthome:
      ansible_user: pi
      ansible_host: smarthome.local
      ansible_become: yes
      tailscale_extra_args: "--accept-dns=false --advertise-exit-node=true"
    printserver:
      ansible_user: pi
      ansible_host: printserver.local
      ansible_become: yes
    streamer:
      ansible_user: pi
      ansible_host: 192.168.0.45
      ansible_become: yes
