all:
  hosts:
    smarthome:
      ansible_user: pi
      ansible_host: smarthome.local
      ansible_become: yes
    printserver:
      ansible_user: pi
      ansible_host: printserver.local
      ansible_become: yes
    streamer:
      ansible_user: pi
      ansible_host: 192.168.1.2
      ansible_become: yes
      tailscale_extra_args: "--accept-dns=false"
