all:
  hosts:
    smarthome:
      ansible_user: pi
      ansible_host: smarthome.local
      ansible_become: yes
      nginx_domain: "home.istrukov.com"
    printserver:
      ansible_user: pi
      ansible_host: printserver.local
      ansible_become: yes
      nginx_domain: "print.istrukov.com"
    streamer:
      ansible_user: pi
      ansible_host: 192.168.1.2
      ansible_become: yes
      tailscale_extra_args: "--accept-dns=false"
      nginx_domain: "pihole.istrukov.com"
