- name: Octoprint server
  hosts: printserver
  roles:
  - tailscale_node
  - octoprint_server

- name: Smart Home Controller
  hosts: smarthome
  roles:
  - tailscale_node
  - pihole
  - home_assistant
