- name: Octoprint server
  hosts: printserver
  roles:
  - octoprint_server
  tags: [ printserver ]

- name: Smart Home Controller
  hosts: smarthome
  roles:
  - home_assistant
  tags: [ smarthome ]

- name: Audio Streamer
  hosts: streamer
  roles:
  - airplay_receiver
  - pihole
  tags: [ streamer ]
