- name: disable avahi-daemon
  systemd:
    name: avahi-daemon
    state: stopped
    enabled: no

- name: run docker container
  community.docker.docker_container:
    name: shairport_sync
    image: istrukov/shairport-sync
    pull: yes
    devices:
    - /dev/snd
    network_mode: host
    restart_policy: unless-stopped
    env:
      AIRPLAY_NAME: "Living Room Audio"
      OUTPUT_DEVICE: "hw:sndrpihifiberry"
