- name: run docker container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole
    pull: yes
    volumes:
    - pihole:/etc/pihole
    - pihole-dnsmasq:/etc/dnsmasq.d"
    restart_policy: unless-stopped
    env:
      TZ: "Europe/Dublin"
      WEBPASSWORD: "{{ pihole_password }}"
    published_ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "8000:80/tcp"
    dns_servers:
    - "193.110.81.0"
    - "185.253.5.0"
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: "3"

- name: generate nginx config
  ansible.builtin.template:
    src: nginx_pihole.j2
    dest: /etc/nginx/sites-available/pihole
    owner: root
    mode: '0600'
  notify: restart nginx

- name: enable nginx config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/pihole
    dest: /etc/nginx/sites-enabled/pihole
    state: link
  notify: restart nginx
